### ISSUE TITLE
关于补全插件的安装，请指教

### ISSUE THREAD

**Issue by ivanberry** [chemzqm/wxapp.vim#2]
**期待**
安装好补全

**已尝试**

- tern 通过npm install tern -g 全局安装
- tern_for_vim 插件安装好
- wxapp.vim 插件安装好，能通过Wxgen component product达到演示效果

**问题**

关于安装中"将tern/wxapp.js"复制至，请指教"tern/wxapp.js"是哪里的文件，具体路径是什么？我是通过NVM管理node版本的。

谢谢

**Comment by chemzqm** [comment]
@ivanberry tern_for_vim 可以支持全局的 tern，但是需要配置 tern 的命令，它默认是使用插件目录下的 tern，你需要在 tern_for_vim 插件目录下执行 npm install, 然后将文件 tern/wxapp.js 拷贝到 tern_for_vim/node_modules/tern/plugin 目录下

**Comment by ivanberry** [comment]
@chemzqm 感谢，是自己的疏忽，tern/wxapp.js既不是tern里的文件，当然也不是tern_for_vim里的文件，理所当然是本插件中tern/wxapp.js,感觉自己问的问题好蠢。 😃 ,感谢，另祝新年快乐~

**Comment by ivanberry** [comment]
@chemzqm   抱歉又来打扰，wxss语法高亮没有起作用，插件生效测试，`=a{`对齐有效果

(![Screen Shot 2017-01-01 at 10.51.05 AM.png](https://ooo.0o0.ooo/2017/01/01/58686eb0f182f.png))

请问开启语法的高亮等，还需要其他设置吗？

**Comment by chemzqm** [comment]
你的高亮或者文件检测没开启吧，
vimrc 中需要有

filetype plugin indent on
syntax on

**Comment by ivanberry** [comment]
```
set encoding=utf-8
set showmatch
set ruler
set nocompatible              " be iMproved, required
set nu!
set relativenumber
set tabstop=2
filetype on                  " required
syntax on 
set background=dark
```

这是部分vimrc配置，另，我只有wxss没有高亮，其他都是没有问题的。

**Comment by chemzqm** [comment]
你在 wxss 文件里使用 `echo &filetype`  返回是啥？

**Comment by chemzqm** [comment]
你把 `filetype on` 改成 `filetype plugin indent on`

**Comment by ivanberry** [comment]
@chemzqm 感谢答疑：
我不知道如何输入你说的指令，直接输入`:echo &filetype`, 没有返回，但是谷歌了下"vim显示文件类型“，`:filetype`,显示以下：

![Screen Shot 2017-01-03 at 9.17.02 AM.png](https://ooo.0o0.ooo/2017/01/03/586afc95ad780.png)

vimrc中filetype改成了，`filetype plugin indent on`

我又google了下，`echo &filetype`检查当前文件类型，返回为空（啥也没有返回），那就意味着vim没有辨别出`wxss`的格式，这优点囧呀，使用`:set filetype=css`后能高亮wxss文件，lol。

**Comment by chemzqm** [comment]
@ivanberry 你在自己的 vimrc 中加入这一行：
```
autocmd BufNewFile,BufRead *.wxss set filetype=wxss
```
看下效果

**Comment by ivanberry** [comment]
@chemzqm It's work, Thank you so much sincerely.
