### ISSUE TITLE
wxml 不能折叠

### ISSUE THREAD

**Issue by Mantak** [chemzqm/wxapp.vim#5]
wxml 无法折叠，怎么破，谢谢

**Comment by chemzqm** [comment]
setlocal foldmethod=indent foldlevelstart=999 foldminlines=0

**Comment by Mantak** [comment]
setlocal foldmethod=indent 
一行就起作用了

可是，我在vimrc里设置了 set foldmethod=indent 
然而，并不起作用，即便是把这行放到了最后，也一样不起作用，
求教，这是为什么，别的文件都可以

**Comment by chemzqm** [comment]
被别的地方设置的覆盖了，写到 after/ftplugin/wxml.vim 里即可

**Comment by Mantak** [comment]
autocmd Filetype wxml setlocal foldmethod=indent 
把上面一行添加到vimrc里，也可以缩进。
但是，
wxml缩进的提示符是 >> ，并且多级缩进 ，会有多个，如：>> >>
普通的缩进提示符是 +--
ps，谢谢如此及时的回复。希望插件越来越美
