### ISSUE TITLE
请问现在 wxml 的语法检查只支持 neomake 吗?

### ISSUE THREAD

**Issue by ghost** [chemzqm/wxapp.vim#6]
有支持 ale, syntastic 的计划吗?

**Comment by chemzqm** [comment]
暂时没有，只做简单的检测应该不会很困难，欢迎 PR。

**Comment by chemzqm** [comment]
请使用 https://github.com/chemzqm/wxml-languageserver
，全面支持语法检查、补全、文档查看。
