### ISSUE TITLE
ubuntu16.04中，wxml和js中的微信api始终无法实现自动补全。

### ISSUE THREAD

**Issue by wsniper** [chemzqm/wxapp.vim#8]
ubuntu16.04中，wxml和js中的微信api始终无法实现自动补全。

**Comment by chemzqm** [comment]
我使用正常，请把问题补充完整。

**Comment by wsniper** [comment]
下面是安装的vim插件列表。tern什么的都安装了。然后，wxapp.vim/tern中的wxapp.json也拷贝到项目的父目录，然后项目中也建立了 .tern-project就是没有js关于wxapi的补全。
snippets应该是能用的，因为输入 Page按tab键可以插入代码片段。


-----------------------------------------------------------------------------------
Plugin 'vim-scripts/TaskList.vim'                                                       |~                                                                                      
Plugin 'gmarik/Vundle'                                                                  |~                                                                                      
Plugin 'posva/vim-vue'                                                                  |~                                                                                      
Plugin 'othree/html5.vim'                                                               |~                                                                                      
Plugin 'SirVer/ultisnips'                                                               |~                                                                                      
Plugin 'ternjs/tern_for_vim'                                                            |~                                                                                      
Plugin 'chemzqm/wxapp.vim'                                                              |~                                                                                      
Plugin 'junegunn/seoul256.vim'                                                          |~                                                                                      
Plugin 'vim-scripts/Pydiction'                                                          |~                                                                                      
Plugin 'vim-scripts/taglist.vim'                                                        |~                                                                                      
Plugin 'skywind3000/asyncrun.vim'                                                       |~                                                                                      
Plugin 'scrooloose/nerdtree'                                                            |~                                                                                      
Plugin 'scrooloose/nerdcommenter'                                                       |~                                                                                      
Plugin 'jistr/vim-nerdtree-tabs'                                                        |~                                                                                      
Plugin 'davidhalter/jedi-vim'                                                           |~                                                                                      
Plugin 'bufexplorer.zip'                                                                |~                                                                                      
Plugin 'Shougo/denite.nvim'                                                             |~                                                                                      
Plugin 'mattn/emmet-vim'                                                                |~                                                                                      
Plugin 'kien/tabman.vim'                                                                |~                                                                                      
Plugin 'rosenfeld/conque-term'                                                          |~                                                                                      
Plugin 'pangloss/vim-javascript'                                                        |~                                                                                      
Plugin 'elzr/vim-json'                                                                  |~                                                                                      
Plugin 'vim-scripts/matchit.zip'                                                        |~                                                                                      
Plugin 'vim-scripts/Css-Pretty'                                                         |~                                                                                      
Plugin 'hail2u/vim-css3-syntax'                                                         |~                                                                                      
Plugin 'hynek/vim-python-pep8-indent'                                                   |~                                                                                      
Plugin 'jmcantrell/vim-virtualenv'                                                      |~                                                                                      
Plugin 'scrooloose/syntastic'                                                           |~                                                                                      
Plugin 'maksimr/vim-jsbeautify'                                                         |~                                                                                      
Plugin 'vimwiki/vimwiki.git'                                                            |~                                                                                      
Plugin 'tlhr/anderson.vim'                                                              |~                                                                                      
Plugin 'chriskempson/tomorrow-theme'                                                    |~                                                                                      
Plugin 'wsniper/vim-github-colorscheme'                                                 |~                                                                                      
Plugin 'nanotech/jellybeans.vim'                                                        |~                                                                                      
Plugin 'tomasr/molokai'                                                                 |~                                                                                      
Plugin 'wsniper/vim-wsniper-colorscheme'                                                |~                                                                                      
                                                                                        |~                                                                                      
~

**Comment by chemzqm** [comment]
@wsniper 项目根目录下的 `.tern-project` 文件配置了吗？
里面要有 
```
{
  "libs": [
    "browser",
    "../wxapp"
  ],
  "loadEagerly": [
  ],
  "plugins": {
    "doc_comment": {},
    "es_modules": {},
    "commonjs": {}
  }
}
```

**Comment by wsniper** [comment]
@chemzqm 完全是按照这个配置的，包括父文件夹的哪个tern的json都有

**Comment by chemzqm** [comment]
@wsniper 应该是 tern 或者你自己的补全插件没配置好导致的问题。

**Comment by wsniper** [comment]
@chemzqm  解决了
步骤：
1. 清理了自己.vimrc .卸载了大部分plugin，删除其配置项目
2. 删除了大部分键的映射
3. 按以下顺序重装wxapp.vim
   - 安装tern_for_vim
   - 在.vim/vimfile/bundle/tern_for_vim/目录下执行： npm install https://github.com/ternjs/tern/tarball/master -S
   - 安装wxapp.vim
   - 在.vimrc 中添加以下配置
         let tern_show_signature_in_pum = 1                                               
         let tern_show_argument_hints = 'on_hold'                                                      
         autocmd FileType javascript setlocal omnifunc=tern#Complete 
然后，按照readme中描述的搞wxapp.json和 .tern_project

万事后重启vim，打开项目中的js 使用 <c-x><c-o>就可以了。
