### ISSUE TITLE
安装 以后 wxml和wxss没有高亮，怎么回事

### ISSUE THREAD

**Issue by xuqinggang** [chemzqm/wxapp.vim#9]
autocmd BufNewFile,BufRead *.wxml set filetype=wxml
我的vim无法识别wxml类型。。。

**Comment by chemzqm** [comment]
你在 vim 命令行执行 `autocmd BufNewFile,BufRead *.wxml set filetype=wxml` 然后在打开 wxml 文件，执行：`:echo &filetype`

**Comment by xuqinggang** [comment]
@chemzqm 在vim中执行好了。。是因为我本地的vim配置和这个冲突了吗？难道每次都要手动执行 `autocmd BufNewFile,BufRead *.wxml set filetype=wxml` ?

**Comment by chemzqm** [comment]
使用命令：`:verbose setl filetype` 看看是哪里的 vim 配置把你的配置覆盖改了，修改掉即可

**Comment by xuqinggang** [comment]
@chemzqm 
![image](https://user-images.githubusercontent.com/13174560/38610856-ae658800-3db4-11e8-8176-0b33d32e3d52.png)
没有发现有配置的地方。。。不过我在自己的vim配置文件里加上 `autocmd BufNewFile,BufRead *.wxml set filetype=wxml`ok了。
谢谢大神。。

**Comment by xuqinggang** [comment]
@chemzqm 好像这个vim插件所有功能，对我都不生效~~。。
